### ISSUE TITLE
Getting "unauthorized" if my api does not have "trading available" checked

### ISSUE THREAD

**Issue by firepol** [Bitrue-exchange/bitrue-official-api-docs#8] opened 2020-11-07 23:07 UTC
Calling the `account` resulted in this response:
```
{"code":-1022,"msg":"UNAUTHORIZED."}
```

I edited the api key and checked the checkbox for "Trading available". That fixed the "unauthorized".

This is very misleading, as I was thinking that "reading" permissions were enough to check my account balances, which is not the case.

This should be documented somewhere.

At least please document the code -1022 and 401 status code. It should be mentioned somewhere in the readme that the api must have basically full access to work.
Read only is not enough.

Cheers

**Comment by snub-fighter** [comment] 2020-11-08 19:55
OK Will close it.  Ill look at adding a note in the README

**Comment by superposition** [comment] 2021-03-23 18:59
Is there anything else because I have checked both boxes and still have the same error

**Comment by acemasterjb** [comment] 2021-03-23 22:55
I'm also getting this error... Not sure why Bitrue say they're [looking for market makers](https://bitrue.zendesk.com/hc/en-001/articles/360041471774-Seeking-Market-Makers-for-Bitrue) when you can't use their API to make trades.

**Comment by superbaby70** [comment] 2021-04-09 18:50
I have the same problem. 
  "code" => -1022
  "msg" => "UNAUTHORIZED."

I think they don't really care about their service, because a lot of errors are staying throw years.
For example try to look at date at Transaction History page, there will be only NaN-aN-aN aN:aN:aN
LOL

**Comment by snub-fighter** [comment] 2021-04-09 19:18
It is true.  Ive given up asking Bitrue about future API developments.   
Unfortunately they have a number of issues to resolve.  
API - advanced features
OCO trades and other advanced options.
Increased load balancing across backend trad platform.   There are constant congestion and heavy load issues that they dont reserve resources for.  

*Personal trade gripe:  Ive had limit orders places for BTR back when it first came out and could have made "10s of 1000s" had the orders filled via GUI and API.  They claimed it was some other issue but that trades never actually hit those prices....   happened multiple times.

**Comment by dxlr8r** [comment] 2021-08-04 22:27
Same issue, atleast on `openOrders`:

```
{"code":-1022,"msg":"UNAUTHORIZED."}
```

On others, like `allOrders`, authentication seems to work*1, but I get:

```
<!DOCTYPE html>
<html>
<head>
<title>Error</title>
<style>
    body {
        width: 35em;
        margin: 0 auto;
        font-family: Tahoma, Verdana, Arial, sans-serif;
    }
</style>
</head>
<body>
<h1>An error occurred.</h1>
<p>Sorry, the page you are looking for is currently unavailable.<br/>
Please try again later.</p>
<p>If you are the system administrator of this resource then you should check
the <a href="http://nginx.org/r/error_log">error log</a> for details.</p>
<p><em>Faithfully yours, OpenResty.</em></p>
</body>
</html>
```
*1: if I do not supply the correct credentials (signature and X-MBX-APIKEY), I get `{"code":-1022,"msg":"UNAUTHORIZED."}`

**Comment by massm90s** [comment] 2021-08-15 12:35
I faced many issues as well, most of which are caused by timestamp. The best approach is to use Bitrue's time.

**Comment by Yoruichi** [comment] 2021-08-18 11:16
{"code":-1022,"msg":"UNAUTHORIZED."}
That usually means no or wrong signature or timestamp in request header.
In my way, i call /api/v1/time first, and set timestamp to the Bitrue server time.

**Comment by Yoruichi** [comment] 2021-08-19 04:15
And we'll provide the detail error message for this code ASAP

**Closed by Yoruichi** 2021-08-19 04:15 UTC
